Task 1 : Prediction using Supervised Machine Learning
GRIP @ The Sparks Foundation
In this regression task I tried to predict the percentage of marks that a student is expected to score based upon the number of hours they studied.

In [11]:
import pandas as pd
from sklearn import linear_model
import numpy as np

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv')

In [3]:
df.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [4]:
df['Hours'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
Name: Hours, dtype: bool

In [5]:
df['Scores'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
Name: Scores, dtype: bool

In [6]:
le=linear_model.LinearRegression()

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(df['Hours'],df['Scores'],test_size=0.2)

In [26]:
x_train=np.stack(x_train)
x_test=np.stack(x_test)

In [14]:
x_train

array([2.5, 5.5, 3.8, 3.2, 1.1, 5.1, 2.7, 2.7, 7.7, 4.8, 7.4, 3.3, 6.9,
       8.3, 8.9, 4.5, 1.9, 2.5, 8.5, 1.5])

In [31]:
x_test

array([[6.1],
       [3.5],
       [9.2],
       [5.9],
       [7.8]])

In [18]:
x_train=x_train.reshape(-1,1)

LinearRegression()

In [17]:
le.fit(x_train,y_train)

In [ ]:
x_test=x_test.reshape(-1,1)

In [28]:
le.score(x_test,y_test)

0.9301542547915985

In [30]:
le.predict([[9.25]])

array([92.00700152])